name: bm
on:
  push:
    branches:
      - main
env:
  NODE_VERSION: 16.15.0
  ARTIFACT_NAME: "bm-dist-gh-pages"
  DEPLOY_TARGET: "bm-github-pages"
defaults:
  run:
    working-directory: apps/bm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: dist
      #     cname: bm.taskratchet.com
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: "dist"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: ${{ env.DEPLOY_TARGET }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@2
        with:
          artifact_name: ${{ env.ARTIFACT_NAME }}
